/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.LocationController;
import daos.LocationDAO;
import icontrollers.ILocationController;
import java.sql.Connection;
import java.util.List;
import javax.swing.JOptionPane;
import models.Location;
import javax.swing.table.DefaultTableModel;
import models.Country;
//import net.sf.ehcache.hibernate.HibernateUtil;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import tools.HibernateUtil;

/**
 *
 * @author hp
 */
public class ViewLocation extends javax.swing.JInternalFrame {

    private LocationController controller;
    private List<Location> listLocation;
    private String[] tableHeader;
    private DefaultTableModel dtm;
    private Connection conn;
//    private Session session;
    private Location location;
    int no;
    int row;
    public ViewLocation viewLocation;
    String Country;
//    private SessionFactory factory;
//    private Transaction transaction;
    SessionFactory factory = HibernateUtil.getSessionFactory();
    Session session;
    Transaction transaction;
    LocationDAO ldao = new LocationDAO(factory);
    private ILocationController controller2;

    /**
     * Creates new form Location
     */
    public ViewLocation() {
        initComponents();
//        Session session =
//        session = factory.openSession();
//        transaction = session.beginTransaction();
        controller2 = new LocationController(factory);
        controller = new LocationController(factory);
        tableHeader = new String[]{"No", "Id", "streetAddress", "postalCode", "city", "stateProvince", "country"};
        dtm = new DefaultTableModel(null, tableHeader);
        tblLocation.setModel(dtm);
        refreshTable();
        tampilCB();
    }

    public void refreshTable() {
//        Location 
        listLocation = controller.getAll();
        dtm = (DefaultTableModel) tblLocation.getModel();
        dtm.setRowCount(0);
        no = 1;
        for (Location l : listLocation) {
            System.out.println("jalan");
            dtm.addRow(new Object[]{
                no++,
                l.getId(),
                l.getStreetAddress(),
                l.getPostalCode(),
                l.getCity(),
                l.getStateProvince(),
                (l.getCountry() == null) ? "" : l.getCountry().getId()//short from dengan pertama adalah kondisi dan setelah : adalah elsenya
            });
        }
        if (tblLocation.getRowCount() > 0) {
            row = tblLocation.getRowCount() - 1;
            tblLocation.setRowSelectionInterval(row, row);
        }
    }

    protected void clearText() {
        txtId.setText(null);
        txtCity.setText(null);
//        txtCountry.setText(null);
        txtStateProvince.setText(null);
        txtStreetAddress.setText(null);
        txtSearch.setText(null);
    }

    public void search() {
        Object[] Line = {"No","ID", "Street Address", "Postal Code", "City", "State Province", "country"};
        dtm = new DefaultTableModel(null, Line);
        String findData = txtSearch.getText();
        try {
            no =1;
            for (Location location : ldao.search(findData)) {
                if (location.getCountry() == null) {
                    location.getCountry();
                }
                System.out.println(location.getId() + " | " + location.getStreetAddress() + " | " + location.getPostalCode() + " | " + location.getCity() + " | " + location.getStateProvince() + " | " + location.getCountry());
                dtm.addRow(new Object[]{
                    no++,
                    location.getId(),
                    location.getStreetAddress(),
                    location.getPostalCode(),
                    location.getCity(),
                    location.getStateProvince(),
                    (location.getCountry() == null) ? "" : location.getCountry().getId()//konsepnya (kondisi)?: if true : if false
                });
            }
            tblLocation.setModel(dtm);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data failed to be called");
        }
    }
        
    public void tampilCB(){
       controller2.searchID();
       listLocation = controller2.searchID();
        for (Object data : listLocation.toArray()) {
            CBCountry.addItem(data.toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPostac = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtStreetAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtStateProvince = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CBCountry = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLocation = new javax.swing.JTable();

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("LOCATION");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(371, 371, 371))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Id");

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Postac Code");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Street Addrees");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("City");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("State Province");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Country Id");

        CBCountry.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CBCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Country - " }));
        CBCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBCountryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPostac)
                    .addComponent(txtId)
                    .addComponent(CBCountry, 0, 137, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtCity, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtStateProvince, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPostac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(txtStateProvince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CBCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnInsert.setText("Save");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 887, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(35, 35, 35)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(5, 5, 5)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearch)
                        .addComponent(btnInsert)
                        .addComponent(btnDelete))
                    .addContainerGap(17, Short.MAX_VALUE)))
        );

        tblLocation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Street Address", "Postal Code", "City", "State Province", "Country ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblLocation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLocationMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLocation);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblLocationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLocationMouseClicked
        int dt = tblLocation.getSelectedRow();
        String a = dtm.getValueAt(dt, 1).toString();
        String b = dtm.getValueAt(dt, 2).toString();
        String c = dtm.getValueAt(dt, 3).toString();
        String d = dtm.getValueAt(dt, 4).toString();
        String e = (dtm.getValueAt(dt, 5)) != null ? (dtm.getValueAt(dt, 5).toString()) : "";
        String f = dtm.getValueAt(dt, 6).toString();
        txtId.setText(a);
        txtStreetAddress.setText(b);
        txtPostac.setText(c);
        txtCity.setText(d);
        txtStateProvince.setText(e);
//        txtCountry(f);
        CBCountry.setSelectedItem(f);
    }//GEN-LAST:event_tblLocationMouseClicked

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        try {
            if (txtId.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "ID hasn't been filled");
                txtId.requestFocus();
            } else {
                if (txtStreetAddress.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Street Address hasn't been filled");
                    txtStreetAddress.requestFocus();
                } else {
                    if (txtCity.getText().isEmpty()) {
                        JOptionPane.showMessageDialog(null, "City hasn't been filled");
                        txtCity.requestFocus();
                    } else {
                        
                controller.saveOrUpdate(Short.parseShort(txtId.getText()),txtStreetAddress.getText(), txtPostac.getText(),txtCity.getText() ,txtStateProvince.getText(), CBCountry.getSelectedItem().toString());
//                        controller.saveOrUpdate(txtId.getText(),txtPostac.getText(),txtCity.getText(),txtStateProvince.getText(), txtCountry.getText());
//                        ldao.saveOrUpdate(txtId.getText(),txtPostac.getText(),txtCity.getText(),txtStateProvince.getText(), txtCountry.getText());
                        JOptionPane.showMessageDialog(null, "Data successfully save");

                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data failed to insert" + e);
        }
        refreshTable();
        clearText();
    }
/*
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {
         try {
            if (txtId.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "ID hasn't been filled");
                txtId.requestFocus();
            } else {
                if (txtStreetAddress.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Street Address hasn't been filled");
                    txtStreetAddress.requestFocus();
                } else {
                    if (txtCity.getText().isEmpty()) {
                        JOptionPane.showMessageDialog(null, "City hasn't been filled");
                        txtCity.requestFocus();
                    } else {
                        
                controller.saveOrUpdate(Short.parseShort(txtId.getText()),txtStreetAddress.getText(), txtPostac.getText(),txtCity.getText() ,txtStateProvince.getText(), txtCountry.getText());
//                        controller.saveOrUpdate(txtId.getText(),txtPostac.getText(),txtCity.getText(),txtStateProvince.getText(), txtCountry.getText());
//                        ldao.saveOrUpdate(txtId.getText(),txtPostac.getText(),txtCity.getText(),txtStateProvince.getText(), txtCountry.getText());
                        JOptionPane.showMessageDialog(null, "Data successfully save");

                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data failed to insert" + e);
        }
        refreshTable();
        clearText();
    }//GEN-LAST:event_btnInsertActionPerformed
*/
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            if (txtId.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "ID hasn't been filled");
                txtId.requestFocus();
            }  else {
                        
                System.out.println(controller.delete(txtId.getText()));
//                        controller.saveOrUpdate(txtId.getText(),txtPostac.getText(),txtCity.getText(),txtStateProvince.getText(), txtCountry.getText());
//                        ldao.saveOrUpdate(txtId.getText(),txtPostac.getText(),txtCity.getText(),txtStateProvince.getText(), txtCountry.getText());
                        JOptionPane.showMessageDialog(null, "Data brhasil");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data failed to insert" + e);
        }
        refreshTable();
        clearText();
    }
/*
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {
       
    }//GEN-LAST:event_btnDeleteActionPerformed
*/
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        search();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void CBCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBCountryActionPerformed
       
    }//GEN-LAST:event_CBCountryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBCountry;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLocation;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPostac;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtStateProvince;
    private javax.swing.JTextField txtStreetAddress;
    // End of variables declaration//GEN-END:variables

}
